### PR TITLE
Support classes for fixture element

### PR DESCRIPTION
**Pull request by ghost**
Hello,

This PR allow to add class to content editor components that use fixtures, exactly like adding class to a normal HTML element. something like this : 

    {% component 'contenteditor' file="test" fixture="p" class="special" %}

It will output something like this

    <p data-fixture="" data-ce-tag="p" data-component="contenteditor::onSave" data-file="test" data-tools="" class="special">

See [this issue](https://github.com/Samuell1/contenteditor/issues/42)

### CODE REVIEW

**Comment by samuelpatro** [comment]
This is cool! Can you please add that class support in 
https://github.com/Samuell1/contenteditor/blob/master/components/contenteditor/render.htm ?

**Comment by ghost** [comment]
Commit added for render.htm

**Comment by samuelpatro** [comment]
I forgot to say PRs needs to be targeted to develop branch. Do you think you can change it to develop?

**Comment by ghost** [comment]
Switched the PR to the develop branch !

**Pull request merged**
