### PR TITLE
Default tools changed from '*' to user specified

### PR DESCRIPTION
**Pull request by michalduda**
1.
When "tools" attribute is empty or not specified in 

`{% component 'contenteditor' tools="*" file="foo.htm" %}`

make the default tools available (chosen in Backend->Settings->Content Editor Settings). 

Currently all ('*') tools are available. 

2.
If no RainLab.Translate locale file for current language exists, use the default file content, eg.: 

if no `content/foo.pl.htm` -> use `content/foo.htm` content. 
After saving - `content/foo.pl.htm` will be created.

Makes the translation process easier for the user (field is not empty, but populated with default text) and prevents ugly October error if no locale file exists and the user is logged out.

### CODE REVIEW

**Comment by samuelpatro** [comment]
Hey, thanks for PR! Can you please do PR to develop branch?

**Comment by michalduda** [comment]
Of course. Sorry I've missed that.

**Comment by samuelpatro** [comment]
Thanks for changed branch, but there are some refactored code and maybe it have some conflicts, can you please check it? This week i want to test it and release new version :)

**Comment by michalduda** [comment]
Hey.

I've looked through the files and:
- contenteditor.js has no conflicts
- ContentEditor.php is, as you say, refactored and therefore some changes have to be made to the commit.

But I think we could translate the logic and change refactored onRender function to look like this:
```
public function onRender()
{
    $this->file = $this->setFile($this->property('file'));
    $this->fixture = $this->property('fixture');
    $this->tools = $this->property('tools');
   
    if ($this->checkEditor()) {
        if (Content::load($this->getTheme(), $this->file)){
            $this->content = $this->renderContent($this->file);
        } else {
            // if no locale file exists -> render the default, without language suffix
            $this->content = $this->renderContent($this->property('file'));
        }
    } else {
        // check if the locale file exists. If no -> render default
        if (Content::load($this->getTheme(), $this->file)){
            return $this->renderContent($this->file);
        } else {
            return $this->renderContent($this->property('file'));
        }
   
    }
}
```
I hope I'll find some time by the end of the week to test how this solution works with the refactored code (worked with the previous) and do the pull request again (properly -> from my forked develop branch).

Unfortunately, I'm not sure if I'll manage to -> having a busy week ;)

Staying in touch!

**Pull request closed without merging**
