### PR TITLE
Add compatibility with StaticPage

### PR DESCRIPTION
**Pull request by haleksandre**
I've added compatibility for RainLab.StaticPages.

The StaticPages plugin doesn't append the default locale to the content blocks filename. In other words, it only appends locales for translated files.

Ex:
```php
// English: en (default)
file.htm

// French: fr
file.fr.htm
```

I've also taken the opportunity to refactor some code in the `onRender()` function to make it cleaner and more readable.

Let me know if everything looks good or you need me to change a few things.

### CODE REVIEW

**Comment by samuelpatro** [comment]
Wow! thanks, i test it and merge it 👍

**Comment by samuelpatro** [comment]
@haleksandre Can you please provide some example how to setup static pages with content editor?

**Comment by haleksandre** [comment]
The steps are the same except you drop the component to the CMS Layout you use for the Static Page. (instead of the CMS Page)

Then Content Editor will detect if the current page is a StaticPage or a CMS Page. If the current page is a StaticPage it will look for Content Blocks created from the StaticPage plugin, which has a different behavior, stated in my pull request description, for translated content block than CMS content block.

It is not possible to use component inside the StaticPage Page content, so this only enables Content Block created from StaticPage plugin to work with the CMS Layout, and/or Snippets.

Let me know if you require more explanation.

**Comment by inerba** [comment]
@haleksandre 
{% component 'contenteditor' file='static-pages/' ~ page.fileName %} instead of {% page %} in CMS layout for static pages?

**Comment by artistro08** [comment]
> {% component 'contenteditor' file='static-pages/' ~ page.fileName %}

That works for me if anyone was wondering

**Pull request merged**
